name: Code Quality

on: [push, pull_request]

jobs:
  code_quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"  # Or your preferred Python version
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 black isort pylint
      - name: Run flake8
        run: flake8 ./custom_components/nec_ha
      - name: Run black (check mode)
        run: black --check ./custom_components/nec_ha
      - name: Run isort (check mode)
        run: isort --check-only --profile black ./custom_components/nec_ha
      - name: Run pylint
        run: pylint ./custom_components/nec_ha
