name: HACS Validation

on:
  push:
    branches:
      - main  # Or your main branch name
  pull_request:  #  Validate on pull requests as well

jobs:
  hacs_validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: HACS Validation
        uses: hacs/action@main
        with:
          category: integration  # Or "plugin", "appdaemon", etc., depending on your component type
          ignore: |
            #  Files or directories to ignore during validation (optional)
            - ".storage"
            - "tests"
