name: Testing

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"  # Or your preferred Python version
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest coverage  #  And any other testing dependencies
          pip install homeassistant  #  If you need Home Assistant libraries for testing
          pip install aiohttp        #  If your code uses aiohttp
      - name: Set up Home Assistant Test Environment (Example - Adjust as needed)
        run: |
          #  This step might involve setting up a minimal Home Assistant
          #  configuration for testing purposes.
          #  For example, creating a configuration.yaml with minimal content.
          echo "Setting up Home Assistant test environment..."
          mkdir -p config
          echo "homeassistant:" > config/configuration.yaml
      - name: Run tests with coverage
        run: |
          coverage run -m pytest tests/  #  Assuming you have a 'tests' directory
          coverage report -m
      - name: Upload coverage to Codecov (Optional)
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: true # Optional: Fail CI if Codecov upload fails
